from selenium import webdriver
from selenium.webdriver.common.by import By
import time
web_browser = webdriver.Chrome()
web_browser.maximize_window()
web_browser.get('http://myousafrana.pythonanywhere.com/')
# web_browser.implicitly_wait(5)
popup1 = web_browser.find_element(By.NAME, 'Your Name')
popup1.clear()
popup1.send_keys('Muhammad Yousaf Rana')
time.sleep(1)
popup2 = web_browser.find_element(By.NAME, 'Your Email')
popup2.clear()
popup2.send_keys('xyz@gmail.com')
time.sleep(1)
popup3 = web_browser.find_element(By.NAME, 'Subject')
popup3.clear()
popup3.send_keys('Automation')
time.sleep(1)
popup4 = web_browser.find_element(By.NAME, 'Message')
popup4.clear()
popup4.send_keys('All of this stuf is done by AutomationTesting in python')
time.sleep(1)
popup5 = web_browser.find_element(By.CSS_SELECTOR, ".contact-form .btn-primary")
popup5.click()
web_browser.implicitly_wait(2)
web_browser.quit()
